version: '2.1'
name: CRT Security Monitor
description: Surveillance camera look
effects:
  crt:
    enabled: true
    warp: 0.15
    scan: 0.9
    aberration: 0.6
    scanline_size: 1.2
    animated: false
    aberration_mode: none
    aberration_speed: 1.0
    glitch: 0.0
    glitch_speed: 1.0
  color_grade:
    vignette_strength: 0.5
    vignette_width: 0.2
    vignette_feather: 0.9
